# Nombre de la app
spring.application.name=Inventario
spring.jpa.hibernate.ddl-auto=update

mylogist.frontend.url=${FRONTEND_URL:https://www.mylogistapp.com}

# ---------------- DataSource ----------------
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/MyLogist?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-test-query=SELECT 1

#----------------- Emails_Google ----------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER:contactomylogist@gmail.com}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ---------------- JPA / Hibernate ----------------
spring.jpa.show-sql=true

# ---------------- Server ----------------
server.port=8080

# ---------------- JWT ----------------
security.jwt.secret=${JWT_SECRET:Clave}
security.jwt.expiration.access-ms=3600000
security.jwt.expiration.refresh-ms=86400000

# ---------------ERRORS------------------
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO
server.error.include-stacktrace=always

# IA Asistente (Groq)
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY:api_key}